import { Fragment } from 'react'
import Head from 'next/head'

import Home from '../components/Home'

export default function HomePage() {
 return (
  <Fragment>
    <Head>
      <title>Google Clone</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Home />
  </Fragment>
 )
}
